config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :posts

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "posts#index"

  get "sign_up", to: "users#new"
  post "sign_up", to: "users#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  post "add-comment", to: "posts#add_comment"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end

  def require_login
    if current_user.nil?
      redirect_to posts_url, notice: "Login required"
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy add_comment ]
  before_action :require_login, except: %i[ index show ]
  skip_before_action :verify_authenticity_token, :only => [:add_comment]

  # GET /posts
  def index
    @posts = Post.all
  end

  # GET /posts/1
  def show
    @comments = @post.comments
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to post_url(@post), notice: "Post was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to post_url(@post), notice: "Post was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy!
    redirect_to posts_url, notice: "Post was successfully destroyed."
  end

  def add_comment
    @post.comments << Comment.create(post: @post, body: params[:comment], user_id: 1)
    @comments = @post.comments
    render partial: "comment"
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:username])

    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to sessions_new_url, notice: "login failed, please try again"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to sign_in_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogu</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if current_user %>
      Logged in as: <%= current_user.first_name + " " + current_user.last_name %> <br>
      <%= button_to "Sign Out", logout_path, method: :delete %>
    <% else %>
      <%= link_to "Sign up", sign_up_path %> | 
      <%= link_to "Sign In", sign_in_path %>
    <% end %>
    <h1>SKY BLOG</h1>
    <%= link_to "All posts", posts_path %> | 
    <%= link_to "New post", new_post_path %>
    <%= yield %>
  </body>
</html>

app/views/posts/_comment.html.erb
<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.user.first_name + " " + comment.user.last_name %></td>
    <td><%= comment.body %></td>
  </tr>
<% end %>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body, class: "body-text" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p class="title">
    <%= post.title %>
  </p>

  <p>
    created: <%= post.created_at.strftime("%m/%d/%Y") %>
  </p>

  <p>
    <%= post.body %>
  </p>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<div id="posts">
  <% @posts.each do |post| %>
    <div class="post">
      <%= render post %>
      <p>
        <%= link_to "Show this post", post %>
      </p>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

app/views/posts/show.html.erb
<script>
  function addComment() {
    var commentArea = document.getElementById("comment-area");
    commentArea.innerHTML= `
      <textarea id="comment"></textarea>
      <button onclick="submitComment()" id="submit-button">Submit Comment</button>
    `;
  }

  function submitComment() {
    var comment = document.getElementById("comment");
    var table = document.getElementById('comments-table');
    fetch(`<%= root_url %>add-comment?comment=${comment.value}&id=<%= @post.id %>`, {method: "post"})
      .then(res => res.text())
      .then(data => table.innerHTML = data);
    document.getElementById("comment-area").innerHTML = '';
  }
</script>

<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %>
  <%= button_to "Destroy this post", @post, method: :delete %>
</div>

<div class="comments-section">
  <h3>comments(<%= @comments.count %>)</h3>
</div>

<table id="comments-table">
  <% @comments.each do |comment| %>
    <tr>
      <td><%= comment.user.first_name + " " + comment.user.last_name %></td>
      <td><%= comment.body %></td>
    </tr>
  <% end %>
</table>

<% if current_user %>
  <div id="add-comment">
    <button onclick="addComment()">Add Comment</button>
  </div>

  <div id="comment-area">
  </div>
<% end %>

app/views/users/new.html.erb
<h2>Sign Up</h2>

<%= form_with model: @user, url: sign_up_path do |f| %>

  <p>
    <%= f.label :First_Name %>
    <%= f.text_field :first_name %>
  </p>

  <p>
    <%= f.label :Last_Name %>
    <%= f.text_field :last_name %>	
  </p>

  <p>
    <%= f.label :username %>
    <%= f.text_field :username %>
  </p>

  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.submit "Sign Up" %>
  </p>
  
<% end %>